trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Drp.launch="Azure Pipeline Run $(Build.BuildId)"'
  displayName: "Run Automation Tests with ReportPortal"